### PR TITLE
Modernize the documentation with jupyter-books 

### LINKED ISSUE #332: update docs to build using jupyter books instead of Sphinx
### Description

The documentation is outdated for both the client and server. There have been many updates on the client side, with the only recent contribution related to the server side is recent PR #318 closing issue #207. 

I would like to start with basic minimal updates to the documentation that a PR would close. The overall goals are

1) Use jupyter books to build the documentation. See https://jupyterbook.org/en/stable/start/overview.html. This requires some overhaul on the documentation patterns / files, etc. 
2) Include capabilities to include executable jupyter notebooks as part of the documentation.

In doing so the following needs to be minimally included:

### Client

- Update examples that demonstrate access various relevant remote data (CMIP6, Earth Data from NASA), and perhaps some plotting/analysis.
- Demonstrate the use of tokens for authentication.
- Exemplify differences when accessing data on servers implementing DAP2 vs DAP4 (some examples can be found in https://github.com/OPENDAP/ESIP2024).

### Server
- Migrate as is. Perhaps many outdated stuff, but there is no need to change anything.

### Other stuff
- Include steps for how to contribute to the code.
- Include steps for how to add and build the documentation

Technically there are already instructions for how to contribute to the code, but are hidden. There are no steps for building / testing the documentation.

### Extra
This are not minimally required to get a PR going. We can include these later.
- Make the API description findable. This implies having docstrings appear in the documentation.
- Include a new section describing `Why pydap?`
- Include a new section describing `What is New?`
- Include a section that describes Datasets/catalogs with known and working OPeNDAP URLs and a Template for adding OPeNDAP URLs. I think this could be potentially useful for allowing a platform for people to make their datasets Discoverable (Findable). Because the code in the documentation will get executed when building the docs - this will help to keep track on broken URLs.

Other suggestions are welcomed. And these can be added later.

### PR DESCRIPTION
**Pull request by Mikejmnez**
The following Pull Request:

- [x] Closes #332 by building a modern-looking documentation for PyDAP.

Instruction for checking the documentation are forthcoming. In the meantime, this is a Draft PR.

### CODE REVIEW

**Comment by Mikejmnez** [comment]
This is what I am looking at when I build the documentation in my computer:


Screenshot 2024-08-02 at 8 23 32 AM

and

Screenshot 2024-08-02 at 8 23 55 AM




Right now I am turning the old documentation files into `md` or `ipynb` files to include them.

**Comment by Mikejmnez** [comment]
This is ready :) .

 I can provide instructions for testing the documentation. Unfortunately, any testing will involve downloading my branch, and building locally the html files.

**Review by jgallagher59701 — APPROVED** [review]
Looks good. I like the PyDAP logo!

**Comment by Mikejmnez** [comment]
Great, we can improve it later, but it looks good for now :)

**Pull request merged**
