### PR TITLE
Do not require gunicorn for a vanilla install

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs reported issues on Widnows when trying to use `pydap`.
See https://gist.github.com/rsignell-usgs/7c9cf9f88a2f0c920c1a4ee7d7eaf601

This PR crates a `server_extras` entry to allow `pydap` to be installed, and usable without, `gunicorn` present.

### CODE REVIEW

**Comment by jameshiebert** [comment]
This looks like a good idea to me (although we do seem to be acquiring a large collection of "extras"). One brief comment, if you set the Python 3.6 classifier (good idea!), can you ensure that py36 is also being testing on TravisCI?

**Comment by ocefpaf** [comment]
> This looks like a good idea to me (although we do seem to be acquiring a large collection of "extras").

Indeed. Would you like to put the `gunicorn` dependency into one of the existing `extras`?

> One brief comment, if you set the Python 3.6 classifier (good idea!), can you ensure that py36 is also being testing on TravisCI?

Done.

**Comment by jameshiebert** [comment]
> Would you like to put the gunicorn dependency into one of the existing extras?

No, I think a "server_extras" makes sense.

Hang tight on that last failed test. I'm going to merge one PR that should take care of that and then you can rebase.

**Comment by jameshiebert** [comment]
OK, if you rebase this PR onto master, the full suite of tests should pass on Travis.

**Comment by ocefpaf** [comment]
> OK, if you rebase this PR onto master, the full suite of tests should pass on Travis.

Done.

**Comment by jameshiebert** [comment]
Perfect, thanks!

**Pull request merged**
