### PR TITLE
Allow Handlers to provide their own criteria for handling the filepat…

### PR DESCRIPTION
**Pull request by neishm**
…h. (#139)

### CODE REVIEW

**Comment by tomkralidis** [comment]
@neishm thanks.  Is `can_handle` a documented handler function?  Should it be?

**Comment by neishm** [comment]
That's a good point.  I'll add some documentation for it in `docs/developer_handlers.rst`.  I'm also open for alternative suggestions on how to choose the appropriate handler for the files.  For instance, Iris has a more sophisticated `FormatAgent` structure which allows you to choose either file extensions or magic byte strings to determine the handler ([source](https://github.com/SciTools/iris/blob/7d0cced495838acc845986f41eb347886117f278/lib/iris/fileformats/__init__.py)).  That might be overkill, though...

**Comment by neishm** [comment]
Some documentation added, still need to create some tests.

**Comment by captainkirk99** [comment]
Is this PR still active?

**Comment by neishm** [comment]
I no longer need this functionality myself.  If nobody else needs it, could be closed without merging.

**Pull request closed without merging**
