### PR TITLE
Add a ``verify`` option to ``open_url``

### PR DESCRIPTION
**Pull request by laliberte**
This PR aims to introduce a ``verify`` option to ``open_url``. When set to ``False`` this option disables ``ssl`` verification in OPENDAP queries. This is important because some servers occasionally have outdated certificates.

While doing do, this PR introduces minor changes to the development server and introduces a new development server that can generate an ad hoc ssl certifcate, based on ``werkzeug``.

### CODE REVIEW

**Comment by tomkralidis** [comment]
@laliberte similar to #106, any chance you can bring this PR up to date against current master?

**Comment by laliberte** [comment]
@tomkralidis this should also be mergeable.

**Comment by tomkralidis** [comment]
Thanks @laliberte. I think there's a new merge conflict as a result of merging #106 first? Can you take a look?

**Comment by laliberte** [comment]
@tomkralidis conflicts merged

**Pull request merged**
