### PR TITLE
Parse timeout value to BaseProxy and SequenceProxy

### PR DESCRIPTION
**Pull request by jgliss**
For details see #269

### CODE REVIEW

**Comment by jgliss** [comment]
@captainkirk99 sorry for bothering you, but could you give me some advice how things are done here when it comes to code improvement suggestions? Cheers!

**Comment by jgliss** [comment]
@owenlittlejohns I just remembered this PR and I am wondering if there is any chance that this could be merged. I am looking into resolving the conflicts against master right now. Since this is a timeout issue that likely only hits in on slow bandwidth connections and large queries I am also a little uncertain whether (and how) to add a test case here, and would only spend further time on this if you consider the change.

**Comment by jgliss** [comment]
@owenlittlejohns I updated the PR and added some simple tests to make sure timeouts are parsed accordingly into the respective proxies. Hope to hear back from you (or someone else that can assess this).

**Comment by jgliss** [comment]
@jgallagher59701 also pinging you on this one and would appreciate it if you could take a look.

**Review by owenlittlejohns — APPROVED** [review]
The changes look good to me - I also kicked off the tests, which passed. I'll give @jgallagher59701 chance to weigh in, but I think this looks good.

**Comment by owenlittlejohns** [comment]
For reference, my test case:

```
dataset = open_url('dap4://opendap.earthdata.nasa.gov/collections/C1996881146-POCLOUD/granules/20230511090000-JPL-L4_GHRSST-SSTfnd-MUR-GLOB-v02.0-fv04.1', timeout=1)
```

**Comment by jgliss** [comment]
Many thanks for looking into this @owenlittlejohns

**Comment by owenlittlejohns** [comment]
Okay. I've merged this and I'll get cracking on the next `pydap` release to PyPI. Thanks, @jgliss for the fix!

**Pull request merged**
