### PR TITLE
add support for THREDDS Catalog XML (#136)

### PR DESCRIPTION
**Pull request by tomkralidis**
This PR implements #136.

### CODE REVIEW

**Comment by neishm** [comment]
This is a very nice feature to have in pydap.  One minor problem I encountered while testing - catalogs in subdirectories were not giving valid URLs.  I found that removing the ```{{ location }}}``` from the ```urlPath``` attributes in ```wsgi/templates/catalog.xml``` seemed to fix that problem for me.

**Comment by tomkralidis** [comment]
@neishm can you provide an example of what you're expecting?

**Comment by neishm** [comment]
For instance, if I have a file **abc** in directory **xyz**, then navigating to `http://localhost:8001/abc/catalog.xml` gives me
```xml
<?xml version="1.0" ?>
<!-- Pydap 3.2.2 -->
<catalog xmlns="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.unidata.ucar.edu/namespaces/thredds/InvCatalog/v1.0 http://www.unidata.ucar.edu/schemas/thredds/InvCatalog.1.0.6.xsd">
    <service name="odap" serviceType="OPeNDAP" base="/xyz/"/>
    <service name="file" serviceType="HTTPServer" base="/xyz/"/>
    <dataset name="abc " ID="/xyz/abc">
        <dataSize units="bytes">333189232</dataSize>
        <date type="modified">2017-02-15T13:13:15.148454</date>
        <access serviceName="odap" urlPath="/xyz/abc"/>
        <access serviceName="file" urlPath="/xyz/abc"/>
    </dataset>
```

If I open this catalog in panoply or IDV, and try to access **abc** from the catalog I get a 404 error.  The reason is it's trying to access `http://localhost:8001/xyz//xyz/abc` (directory name repeated).

Checking the [THREDDS docs](http://www.unidata.ucar.edu/software/thredds/current/tds/tutorial/CatalogPrimer.html#Constructing_an_access_URL), looks like it's combining the **base**+ **urlPath** to get the final URL on the client side.  So, I think either **base** should just be "/", or the **urlPath** should exclude the directory structure (e.g., just be "abc" in this example).  I tested the latter approach, and that resolved the issue for me.

Would really like to have THREDDS catalog support for pydap.  Already testing out your branch on our local server, and it makes things a lot easier to navigate our datasets remotely.

**Comment by tomkralidis** [comment]
@neishm thanks for the info.  I'll look into this tonight. The important item is validating this against the specification, and thanks for pointing to the THREDDS docs.

Aside: can you contact me for an offline question? tom.kralidis@gmail.com

**Pull request merged**
