### PR TITLE
Import ABC from collections.abc instead of collections for Python 3 compatibility

### LINKED ISSUE #203: Deprecations about imports from collections
The `Mapping` import causes a deprecation warning and will be removed in 3.9:
```
.../pydap/model.py:175
  .../pydap/model.py:175: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import OrderedDict, Mapping
```
Also, `Iterable`:
```
.../pydap/responses/das.py:14
  .../pydap/responses/das.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable
```

### PR DESCRIPTION
**Pull request by tirkarthi**
Fixes #203

### CODE REVIEW

**Comment by theochit** [comment]
Is this supposed to be `collections.abc` instead of `collections_abc`? Just from a quick glance at the TravisCI failures, I could be wrong.

**Comment by tirkarthi** [comment]
six added a move for this. It seems an older version of six is used in the project. I will update the PR.

**Comment by theochit** [comment]
Thanks @tirkarthi :)

**Comment by Illviljan** [comment]
Hello, When will this PR be merged? pydap is not usable in python 3.10 at the moment for (at least) this reason.

**Comment by captainkirk99** [comment]
I don't understand why the Jenkins CI was not run on this PR.

**Comment by captainkirk99** [comment]
OK, these changes were merged with PR #243. I will close this PR.

**Pull request closed without merging**
