### PR TITLE
Np2

### LINKED ISSUE #321: `pydap` appears to be incompatible with `numpy>=2`
### Description

Importing `pydap.client` fails if `numpy>=2` is installed (noticed in `xarray`'s CI).

### Minimal example that reproduces the bug, or a new desired feature

With `numpy>=2` in the environment:

```pytb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pydap.client

File .../lib/python3.11/site-packages/pydap/client.py:53
     51 import pydap.lib
     52 import pydap.net
---> 53 import pydap.handlers.dap
     54 import pydap.parsers.dds
     55 import pydap.parsers.dmr

File .../lib/python3.11/site-packages/pydap/handlers/dap.py:16
     14 import re
     15 from itertools import chain
---> 16 from numpy.lib.arrayterator import Arrayterator
     18 # handlers should be set by the application
     19 # http://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library
     20 import logging

ModuleNotFoundError: No module named 'numpy.lib.arrayterator'
```

<details><summary>Environment</summary>

```
python : 3.11.9 (conda-forge)
numpy: 2.0.0
pydap: 3.4.0
```

</details>

### PR DESCRIPTION
**Pull request by Mikejmnez**
The following Pull Request:

- [x] Closes #321 
- [x] Tests are added to incorporate new behavior
- [x] Fixes docs and docstring  to display behavior with numpy 2 and Sequences.

### CODE REVIEW

**Comment by Mikejmnez** [comment]
With Numpy = 2, a sequence now displays data slightly different. Consider the following example:
## Setup of example
```python
        >>> import numpy as np
        >>> data = np.array([
        ... (10, 15.2, 'Diamond_St'),
        ... (11, 13.1, 'Blacktail_Loop'),
        ... (12, 13.3, 'Platinum_St'),
        ... (13, 12.1, 'Kodiak_Trail')],
        ... dtype=np.dtype([
        ... ('index', np.int32), ('temperature', np.float32),
        ... ('site', np.dtype('|S14'))]))
        ...
        >>> seq = SequenceType('example')
        >>> seq['index'] = BaseType('index')
        >>> seq['temperature'] = BaseType('temperature')
        >>> seq['site'] = BaseType('site')
        >>> seq.data = data
```
###    Iteraring over the sequence to print data:

```python
        >>> for line in seq.iterdata():
        ...     print(line)
        (np.int32(10), np.float32(15.2), 'Diamond_St')
        (np.int32(11), np.float32(13.1), 'Blacktail_Loop')
        (np.int32(12), np.float32(13.3), 'Platinum_St')
        (np.int32(13), np.float32(12.1), 'Kodiak_Trail')

```
Note the `np.type` for each element of the array. 

### Before , the same code would print

```python
        (10, 15, 'Diamond_St')
        (11, 13.1, 'Blacktail_Loop')
        (12, 13.3, 'Platinum_St')
        (13, 12.1, 'Kodiak_Trail')
```
## Why?
With numpy 2 the following code throws an error

The change alone  introduced many errors. which required the change here
https://github.com/pydap/pydap/blob/e133372aea4f033b950c1137953dfd8b97c81b88/src/pydap/responses/dods.py#L45-L46

The error arises because newbytesorder is no longer a method of `x.astype` ...

**Comment by Mikejmnez** [comment]
I found this simple way to decode the representation of numpy types into native Python types, with a slight modification to the following function. This would allow to revert all the changes to the documentation. That is, change the following function:
https://github.com/pydap/pydap/blob/e133372aea4f033b950c1137953dfd8b97c81b88/src/pydap/lib.py#L330-L335

To

```python
def decode_np_strings(numpy_var): 
    """Given a fixed-width numpy string, decode it to a unicode type""" 
    if isinstance(numpy_var, bytes) and hasattr(numpy_var, "tobytes"): 
        return numpy_var.tobytes().decode("utf-8") 
    else:
        if isinstance(numpy_var, np.generic):
            # starting with numpy 2.0 need to explicitly convert
            # numpy scalar to native Python type
            return numpy_var.item()
        else: 
            return numpy_var
```

However the new decode_np_strings yields now

```python
        >>> for line in seq.iterdata():
        ...     print(line)
    (10, 15.199999809265137, 'Diamond_St')
    (11, 13.100000381469727, 'Blacktail_Loop')
    (12, 13.300000190734863, 'Platinum_St')
    (13, 12.100000381469727, 'Kodiak_Trail')
```
instead of 
>
>        (10, 15, 'Diamond_St')
>        (11, 13.1, 'Blacktail_Loop')
>        (12, 13.3, 'Platinum_St')
>        (13, 12.1, 'Kodiak_Trail')
>
>

Nothing wrong - since this is the inherent precision of `np.float32`, but it may lead to the wrong interpretation that pydap is somehow changing the data.




### Thus
I decided NOT to change `np.decode_string` and instead change the documentation

**Comment by Mikejmnez** [comment]
@jgallagher59701 ready for merger

**Review by jgallagher59701 — APPROVED** [review]
Ready to merge. Thanks!

**Comment by Mikejmnez** [comment]
Awesome, thanks!

**Pull request merged**
