### PR TITLE
change encoding of NaN values (#148)

### LINKED ISSUE #148: Issues with encoding of NaN
It seems that the NetCDF-Java OPeNDAP client has a problem with pydap's encoding of NaN (e.g. in the DAS response). Some clients seem to only parse 'NaN', while pydap encodes it as 'nan'.

The DAP2 specification does not mention NaN at all, IEEE754 does not specify any string representation of NaN. http://www.unidata.ucar.edu/mailing_lists/archives/thredds/2016/msg00145.html
According to the link above it looks like THREDDS changed to using NaN.

### PR DESCRIPTION
**Pull request by pauleckhardt**
fixes #148

### CODE REVIEW

**Comment by laliberte** [comment]
@pauleckhardt could you add a test that checks your implementation?

**Comment by tomkralidis** [comment]
@pauleckhardt any chance you can update based on current master and add a test?

**Comment by captainkirk99** [comment]
Is this PR still active? There are some conflicts to be resolved...

**Comment by Mikejmnez** [comment]
Is this PR active?

**Comment by Mikejmnez** [comment]
I have decided to close this PR. Because:

- [x] The base code has change a lot, with many conflicts to resolve.
- [x] This PR is related to [pydap/#148](https://github.com/pydap/pydap/issues/148), opened in 2017. Several of us tried to check if this is active or not, with no response. At the very least this PR is stale.
- [x] The code still needs work.
- [x] If the original issue (from 2017!) persists, I think it makes more sense to update the fork with the most up-to-date branch of pydap's repo, and re submit.

**Pull request closed without merging**
