### PR TITLE
set up pre-commit on github actions

### PR DESCRIPTION
**Pull request by Mikejmnez**
The following Pull Request:

- [x] Closes an already existing opened issue #311 requesting
a new feature, etc.
- [x] Tests are not needed since this is about gh actions - no change to code

### CODE REVIEW

**Comment by Mikejmnez** [comment]
Hmm. Two things going on:

1) tests with macOs fail with the following error:
```
 Error: The version '3.9' with architecture 'arm64' was not found for macOS 14.4.1.
```
This is being reported since yesterday in here [actions/setup-python#850](https://github.com/actions/setup-python/issues/850). It looks like the issue is due to
>  `macos-latest` now uses M1 runners (`macos-14-arm64`) and 3.9 and earlier aren't available there: [#696 (comment)](https://github.com/actions/setup-python/issues/696#issuecomment-1637587760)
> To fix, you can use one of the options at [python/peps#3763](https://github.com/python/peps/pull/3763), or stick to `macos-12` or `macos-13` (but you get some [nice speedups](https://github.com/python-pillow/Pillow/pull/7766) using M1 where available).


2) `pre-commit` is failing when running flake8 on a test file.
```python
src/pydap/tests/dap_4_access/dap4_access_test.py:73:47: E226 missing whitespace around arithmetic operator
```
 I noticed that `pre-commit` is running `python 3.12`, whereas no other action is running that version of python. It is possible the error is due to that. Or that when running this action, pre-commit is not using the exact configurations from the `pre-commit-config.yaml` file on the root. 


I will investigate these tomorrow.

**Comment by Mikejmnez** [comment]
woohoo!

**Comment by Mikejmnez** [comment]
woohoo! 
I had to remove python 3.9 from macos-latest from github actions because the runners on "macos-latest" are all M1. To run tests with python 3.9 on `mac-os` we'd have to define a separate `runs-on: macos-13` yaml file.

**Comment by Mikejmnez** [comment]
@jgallagher59701 This is ready for review. As you can see `pre-commit` is now running on GH actions starting on this PR.

**Comment by jgallagher59701** [comment]
Yes, this looks ready to merge. Thanks!

**Review by jgallagher59701 — APPROVED** [review]
Merge! Thanks.

**Pull request merged**
