### PR TITLE
Fix CEDA openid authentication

### PR DESCRIPTION
**Pull request by laliberte**
This PR fixes the authentication scheme to ensure that CEDA openids are working. It also includes a test to prevent regressions.

This fix replaces the ``mechanicalsoup`` dependency with ``beautifulsoup4``. I think this is for the best since ``beautifulsoup4`` is a generally better maintained package.

### CODE REVIEW

**Comment by laliberte** [comment]
This fixes #103. @jameshiebert could you review next week?

**Comment by jameshiebert** [comment]
Do you have a run on Travis with the auth switch turned on (and all of the CEDA environment variables set)? I mean, I trust that this works, but it'd be good to confirm.

**Comment by laliberte** [comment]
Give me a few hours and I'll do this!

Fred

**Comment by laliberte** [comment]
@jameshiebert I've converted CAS tests to ``pytest``. These tests are now skipped if the required environment variables are not set. They can still be skipped with ``py.test -a 'not auth'``. This way, a contributor (e.g. me) can set their travis environment to pass those tests but it does not require the main repository to pass them. This means that in the future when a PR passes my Travis then these tests will be successful.

**Comment by jameshiebert** [comment]
Yeah, that's cool the way that you did that! Unfortunately (or... fortunately that we caught it?)... these [tests failed on your TravisCI](https://travis-ci.org/laliberte/pydap/builds/234996386)...

**Comment by laliberte** [comment]
Darn!

**Pull request merged**
